name: Build Linux Binary

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust musl target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build static binary
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-executable
          path: target/x86_64-unknown-linux-musl/release/linux_forge
